"""Generate gunboat-port/src/symbols.hpp from reverse_engineering/symbols.csv.

  DGROUP globals          constexpr u16 DS_<name> = 0xXXXX;      (ds_u8/ds_u16/... from mem.hpp)
  code-segment globals    constexpr u16 CS_<name> = 0xXXXX;      (offset in its segment)
                          constexpr u16 CSSEG_<name> = 0xSSSS;   (file segment: seg_u8(CSSEG_x, CS_x))
  functions               constexpr u32 FN_<name> = 0xSSSSOOOO;  (file segment:offset, for comments,
                                                                  traces and the test bridge)
Leading underscores are dropped (C++ reserves "__"); a name that then collides gets its address as a
suffix. Owner and type are kept as a comment. Adapted from test-drive-3-sdl3/tools/gen_symbols.py
(MIT, (c) 2026 Krzysztof Kania).

usage: gen_symbols.py      (after merge_symbols.py and symbols.py)
"""
import csv
import os
import re
from collections import Counter

RE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.dirname(RE)
DST = os.path.join(ROOT, 'gunboat-port', 'src', 'symbols.hpp')


def ident(name):
    name = re.sub(r'\W', '_', name).lstrip('_')
    return ('_' + name) if name[:1].isdigit() else name


def key(r):
    a = r['address']
    if a.upper().startswith('DS:'):
        return (0, 0, int(a[3:], 16))
    s, o = a.split(':')
    return (1, int(s, 16), int(o, 16))


def comment(r):
    typ = r['type'].replace('*/', '* /')[:48]
    return '// %s%s' % (r['owner'], (', ' + typ) if typ else '')


def main():
    with open(os.path.join(RE, 'symbols.csv'), newline='', encoding='utf-8') as fh:
        rows = list(csv.DictReader(fh))
    ds = sorted((r for r in rows if r['kind'] == 'global'), key=key)
    cs = sorted((r for r in rows if r['kind'] == 'cglobal'), key=key)
    fn = sorted((r for r in rows if r['kind'] == 'func'), key=key)

    out = ['// Generated by reverse_engineering/tools/gen_symbols.py from reverse_engineering/symbols.csv.',
           '// Do not edit: rename in the spec symbol files, merge, validate and regenerate.',
           '#pragma once',
           '#include "types.hpp"',
           '',
           'namespace gb {',
           '']
    for title, sel, prefix in (('DGROUP globals: offsets for ds_u8/ds_u16/...', ds, 'DS_'),
                               ('Code-segment globals: CS_x offset in file segment CSSEG_x', cs, 'CS_'),
                               ('Original functions: file segment << 16 | offset', fn, 'FN_')):
        counts = Counter(ident(r['name']) for r in sel)
        out.append('// ---- %s' % title)
        for r in sel:
            n = ident(r['name'])
            k = key(r)
            if counts[n] > 1:
                n = '%s_%04X' % (n, k[2]) if k[0] == 0 else '%s_%04X_%04X' % (n, k[1], k[2])
            if prefix == 'DS_':
                out.append('constexpr u16 %-40s = 0x%04X;  %s' % ('DS_' + n, k[2], comment(r)))
            elif prefix == 'CS_':
                out.append('constexpr u16 %-40s = 0x%04X;  %s' % ('CS_' + n, k[2], comment(r)))
                out.append('constexpr u16 %-40s = 0x%04X;' % ('CSSEG_' + n, k[1]))
            else:
                out.append('constexpr u32 %-40s = 0x%04X%04X;  %s' % ('FN_' + n, k[1], k[2], comment(r)))
        out.append('')
    out.append('} // namespace gb')
    out.append('')
    with open(DST, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write('\n'.join(out))
    print('wrote %s: %d DGROUP globals, %d code-segment globals, %d functions'
          % (os.path.relpath(DST, ROOT), len(ds), len(cs), len(fn)))


if __name__ == '__main__':
    main()
